In [1]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns

In [2]:
df= pd.read_csv('train.csv')

In [3]:
df.shape

(404290, 6)

In [4]:
df.head()

,id,qid1,qid2,question1,question2,is_duplicate
0,0,1,2,What is the step by step guide to invest in sh...,What is the step by step guide to invest in sh...,0
1,1,3,4,What is the story of Kohinoor (Koh-i-Noor) Dia...,What would happen if the Indian government sto...,0
2,2,5,6,How can I increase the speed of my internet co...,How can Internet speed be increased by hacking...,0
3,3,7,8,Why am I mentally very lonely? How can I solve...,Find the remainder when [math]23^{24}[/math] i...,0
4,4,9,10,"Which one dissolve in water quikly sugar, salt...",Which fish would survive in salt water?,0

In [5]:
new_df = df.sample(30000)

In [6]:
new_df.isnull().sum()

id              0
qid1            0
qid2            0
question1       0
question2       0
is_duplicate    0
dtype: int64

In [8]:
new_df.duplicated().sum()

0

In [9]:
ques_df = new_df[['question1','question2']]
ques_df.head()

,question1,question2
58028,How can one start developing a chat bot using ...,How do I learn Natural Language Processing?
140959,Why are gases not affected by gravity?,Does gravity affect energy?
180264,"What do the lyrics mean in ""Vienna"" by Billy J...",What is the best Billy Joel song and why?
176417,How many servers is an ISP required to have?,What will be the best ISP in USA for hosting w...
108113,Why do you believe in astrology?,Astrology Believers: What are some specific re...

In [10]:
from sklearn.feature_extraction.text import CountVectorizer
questions = list(ques_df['question1']) + list(ques_df['question2'])
cv = CountVectorizer(max_features=3000)
q1_arr, q2_arr = np.vsplit(cv.fit_transform(questions).toarray(),2)

In [11]:
temp_df1 = pd.DataFrame(q1_arr, index= ques_df.index)
temp_df2 = pd.DataFrame(q2_arr, index= ques_df.index)
temp_df = pd.concat([temp_df1, temp_df2], axis=1)
temp_df.shape

(30000, 6000)

In [12]:
temp_df

,0,1,2,3,4,5,6,7,8,9,...,2990,2991,2992,2993,2994,2995,2996,2997,2998,2999
58028,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
140959,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
180264,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
176417,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
108113,0,0,0,0,0,0,0,0,0,0,...,0,0,0,1,0,0,0,0,0,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
190917,0,0,0,0,0,0,0,0,0,0,...,0,0,0,1,0,0,0,0,0,0
368220,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
15186,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
403341,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
48108,0,0,0,0,0,0,0,0,0,0,...,0,0,0,2,0,0,0,0,0,0

In [13]:
temp_df['is_duplicate'] = new_df['is_duplicate']

In [14]:
temp_df.head()

,0,1,2,3,4,5,6,7,8,9,...,2991,2992,2993,2994,2995,2996,2997,2998,2999,is_duplicate
58028,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
140959,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
180264,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
176417,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
108113,0,0,0,0,0,0,0,0,0,0,...,0,0,1,0,0,0,0,0,0,1

In [17]:
from sklearn.model_selection import train_test_split
X_train,X_test,y_train,y_test = train_test_split(temp_df.iloc[:,0:-1].values,temp_df.iloc[:,-1].values,test_size=0.2,random_state=1)

In [18]:
from sklearn.ensemble import RandomForestClassifier
from sklearn.metrics import accuracy_score
rf = RandomForestClassifier()
rf.fit(X_train,y_train)
y_pred = rf.predict(X_test)
accuracy_score(y_test,y_pred)

0.7426666666666667

In [21]:
from xgboost import XGBClassifier
xgb = XGBClassifier()
xgb.fit(X_train,y_train)
y_pred = xgb.predict(X_test)
accuracy_score(y_test,y_pred)

0.721

In [20]:
pip install xgboost

Defaulting to user installation because normal site-packages is not writeableNote: you may need to restart the kernel to use updated packages.

Collecting xgboost
  Downloading xgboost-3.4.1-py3-none-win_amd64.whl.metadata (2.0 kB)
Requirement already satisfied: numpy in c:\programdata\anaconda3\lib\site-packages (from xgboost) (1.26.4)
Requirement already satisfied: scipy in c:\programdata\anaconda3\lib\site-packages (from xgboost) (1.13.1)
Downloading xgboost-3.4.1-py3-none-win_amd64.whl (48.9 MB)
   ---------------------------------------- 0.0/48.9 MB ? eta -:--:--
    --------------------------------------- 0.8/48.9 MB 8.5 MB/s eta 0:00:06
   - -------------------------------------- 1.8/48.9 MB 4.8 MB/s eta 0:00:10
   -- ------------------------------------- 2.6/48.9 MB 4.4 MB/s eta 0:00:11
   -- ------------------------------------- 3.4/48.9 MB 4.2 MB/s eta 0:00:11
   --- ------------------------------------ 3.9/48.9 MB 4.0 MB/s eta 0:00:12
   --- ------------------------------------ 4.5/48.9 MB 3.5 MB/s eta 0:00:13
   ---- ----------------------------------- 5.5/48.9 MB 3.7 MB/s eta 0:00:12
   ----- ---------------------------------- 6.6/48.9 MB 3.8 MB/s eta 0:00:12
   ----- ---------------------------------- 7.3/48.9 MB 3.8 MB/s eta 0:00:12
   ------ --------------------------------- 8.1/48.9 MB 3.8 MB/s eta 0:00:11
   ------- -------------------------------- 8.9/48.9 MB 3.8 MB/s eta 0:00:11
   ------- -------------------------------- 9.7/48.9 MB 3.8 MB/s eta 0:00:11
   -------- ------------------------------- 10.5/48.9 MB 3.8 MB/s eta 0:00:11
   --------- ------------------------------ 11.3/48.9 MB 3.8 MB/s eta 0:00:10
   --------- ------------------------------ 11.5/48.9 MB 3.7 MB/s eta 0:00:11
   --------- ------------------------------ 11.8/48.9 MB 3.5 MB/s eta 0:00:11
   ---------- ----------------------------- 12.6/48.9 MB 3.4 MB/s eta 0:00:11
   ---------- ----------------------------- 13.4/48.9 MB 3.4 MB/s eta 0:00:11
   ----------- ---------------------------- 13.6/48.9 MB 3.5 MB/s eta 0:00:11
   ----------- ---------------------------- 13.6/48.9 MB 3.5 MB/s eta 0:00:11
   ----------- ---------------------------- 13.9/48.9 MB 3.1 MB/s eta 0:00:12
   ----------- ---------------------------- 14.4/48.9 MB 3.0 MB/s eta 0:00:12
   ----------- ---------------------------- 14.7/48.9 MB 3.0 MB/s eta 0:00:12
   ----------- ---------------------------- 14.7/48.9 MB 3.0 MB/s eta 0:00:12
   ----------- ---------------------------- 14.7/48.9 MB 3.0 MB/s eta 0:00:12
   ----------- ---------------------------- 14.7/48.9 MB 3.0 MB/s eta 0:00:12
   ------------ --------------------------- 14.9/48.9 MB 2.6 MB/s eta 0:00:14
   ------------ --------------------------- 15.2/48.9 MB 2.5 MB/s eta 0:00:14
   ------------ --------------------------- 15.5/48.9 MB 2.5 MB/s eta 0:00:14
   ------------- -------------------------- 16.3/48.9 MB 2.5 MB/s eta 0:00:14
   -------------- ------------------------- 17.6/48.9 MB 2.6 MB/s eta 0:00:13
   -------------- ------------------------- 17.8/48.9 MB 2.6 MB/s eta 0:00:12
   --------------- ------------------------ 18.6/48.9 MB 2.6 MB/s eta 0:00:12
   --------------- ------------------------ 19.4/48.9 MB 2.6 MB/s eta 0:00:12
   ---------------- ----------------------- 20.4/48.9 MB 2.7 MB/s eta 0:00:11
   ----------------- ---------------------- 21.2/48.9 MB 2.7 MB/s eta 0:00:11
   ----------------- ---------------------- 22.0/48.9 MB 2.8 MB/s eta 0:00:10
   ------------------ --------------------- 22.8/48.9 MB 2.8 MB/s eta 0:00:10
   ------------------- -------------------- 23.9/48.9 MB 2.8 MB/s eta 0:00:09
   -------------------- ------------------- 24.6/48.9 MB 2.8 MB/s eta 0:00:09
   -------------------- ------------------- 25.4/48.9 MB 2.9 MB/s eta 0:00:09
   --------------------- ------------------ 26.2/48.9 MB 2.9 MB/s eta 0:00:08
   --------------------- ------------------ 26.5/48.9 MB 2.9 MB/s eta 0:00:08
   --------------------- ------------------ 26.7/48.9 MB 2.9 MB/s eta 0:00:08
   ---------------------- ----------------- 27.3/48.9 MB 2.8 MB/s eta 0:00:08
   ---------------------- ----------------- 28.0/48.9 MB 2.8 MB/s eta 0:00:08
   ----------------------- ---------------- 28.8/48.9 MB 2.8 MB/s eta 0:00:08
   ------------------------ --------------- 29.9/48.9 MB 2.9 MB/s eta 0:00:07
   ------------------------ --------------- 30.4/48.9 MB 2.9 MB/s eta 0:00:07
   ------------------------- -------------- 30.9/48.9 MB 2.9 MB/s eta 0:00:07
   -------------------------- ------------- 32.2/48.9 MB 2.9 MB/s eta 0:00:06
   -------------------------- ------------- 32.8/48.9 MB 2.9 MB/s eta 0:00:06
   --------------------------- ------------ 33.8/48.9 MB 3.0 MB/s eta 0:00:06
   ---------------------------- ----------- 34.6/48.9 MB 3.0 MB/s eta 0:00:05
   ---------------------------- ----------- 35.4/48.9 MB 3.0 MB/s eta 0:00:05
   ----------------------------- ---------- 35.9/48.9 MB 3.0 MB/s eta 0:00:05
   ----------------------------- ---------- 36.7/48.9 MB 3.0 MB/s eta 0:00:05
   ------------------------------ --------- 37.7/48.9 MB 3.0 MB/s eta 0:00:04
   ------------------------------- -------- 38.3/48.9 MB 3.0 MB/s eta 0:00:04
   ------------------------------- -------- 38.8/48.9 MB 3.0 MB/s eta 0:00:04
   -------------------------------- ------- 39.6/48.9 MB 3.0 MB/s eta 0:00:04
   -------------------------------- ------- 39.8/48.9 MB 3.0 MB/s eta 0:00:04
   --------------------------------- ------ 40.9/48.9 MB 3.0 MB/s eta 0:00:03
   ---------------------------------- ----- 41.7/48.9 MB 3.0 MB/s eta 0:00:03
   ---------------------------------- ----- 42.2/48.9 MB 3.0 MB/s eta 0:00:03
   ---------------------------------- ----- 42.5/48.9 MB 3.0 MB/s eta 0:00:03
   ---------------------------------- ----- 42.7/48.9 MB 3.0 MB/s eta 0:00:03
   ----------------------------------- ---- 43.5/48.9 MB 3.0 MB/s eta 0:00:02
   ------------------------------------ --- 44.3/48.9 MB 3.0 MB/s eta 0:00:02
   ------------------------------------- -- 45.4/48.9 MB 3.0 MB/s eta 0:00:02
   ------------------------------------- -- 46.1/48.9 MB 3.0 MB/s eta 0:00:01
   -------------------------------------- - 46.9/48.9 MB 3.0 MB/s eta 0:00:01
   -------------------------------------- - 47.7/48.9 MB 3.0 MB/s eta 0:00:01
   ---------------------------------------  48.5/48.9 MB 3.0 MB/s eta 0:00:01
   ---------------------------------------  48.8/48.9 MB 3.0 MB/s eta 0:00:01
   ---------------------------------------- 48.9/48.9 MB 3.0 MB/s eta 0:00:00
Installing collected packages: xgboost
Successfully installed xgboost-3.4.1